### ISSUE TITLE
Efficiency

### ISSUE THREAD

**Issue by funny-falcon** [seiflotfy/cuckoofilter#1]
Cuckoo filter should be memory and CPU efficient.
Using "slice" for buckets and fingerprints destroys both cause sizeof(slice)==24byte and every slice is a pointer inderection.

**Comment by seiflotfy** [comment]
good call... fixing it asap

**Comment by seiflotfy** [comment]
I partially fixed it... a bucket is now an array of fp instead of a slice. still need to change fingerprints (and loose the 0 as a value for a fp)

**Comment by funny-falcon** [comment]
note, that paper propose usage of 12-bit "fingerprints" as "better than bloom filter".
8-bit has less memory efficiency for same "false positive" answer.

Next: probalistic filter has no operation "delete" - neither "bloom filter" nor "cuckoo filter" can know how much items are collided.

**Comment by seiflotfy** [comment]
i was thinking of going up to 16 bits because working with 12 bits would have been painful for a start

**Comment by seiflotfy** [comment]
Ok I fixed the slices issues. Now everything is array :D

**Comment by seiflotfy** [comment]
@funny-falcon so i ran through most of the optimisations you recommended and it works great.
Would you be interested in helping me out with the 12 bit fingerprint func?
