### ISSUE TITLE
Reduce repetition in naming

### ISSUE THREAD

**Issue by mholt** [seiflotfy/cuckoofilter#19]
Not a big deal, but `cuckoofilter.NewCuckooFilter()` is a bit repetitive for my taste -- would you be open to renaming the types/functions to `New()` and `NewDefault()` (not sure if NewDefault is really necessary either, if you want to shrink your API surface a bit) and `Filter`?

In fact, the package could be renamed to just `cuckoo` and then you'd have `cuckoo.NewFilter()` and `cuckoo.Filter` which is a little more natural.

Just my 2 cents!

**Comment by seiflotfy** [comment]
yeah can you create a PR... Love it
