### ISSUE TITLE
getAltIndex implementation problem

### ISSUE THREAD

**Issue by jared-nishikawa** [seiflotfy/cuckoofilter#26]
Given what I know about cuckoo filters, given a fingerprint f there should be two indices i1 and i2 such that i1 ^ f = i2.

The problem is in util.go, here:
```
func getAltIndex(fp byte, i uint, numBuckets uint) uint {
	hash := uint(metro.Hash64([]byte{fp}, 1337))
	return (i ^ hash) % numBuckets
}
```

For example, take f = 216, i = 8, and numBuckets = 100 (example taken when `data = []byte("hello world")`)

Then `getAltIndex(216, 8, 100) = 70`

One would expect that `getAltIndex(216, 70, 100)` would produce 8.  However, this is not the case:

`getAltIndex(216, 70, 100) = 36`

I believe the problem is the implementation of `getAltIndex`.  Basically, xor (^) and mod (%) do not commute, and the modulo operation needs to be done first.  That is:

```
func getAltIndex(fp byte, i uint, numBuckets uint) uint {
	hash := (uint(metro.Hash64([]byte{fp}, 1337))) % numBuckets
	return (i % numBuckets) ^ hash
}
```

This produces the desired result.

**Comment by seiflotfy** [comment]
Makes sense, can you open a pr?
