### ISSUE TITLE
../pkg/mod/github.com/seiflotfy/cuckoofilter@v0.0.0-20200323075608-c8f23b6b6cef/util.go:17:14: invalid operation: 1 << i (shift count type int, must be unsigned integer)

### ISSUE THREAD

**Issue by neboduus** [seiflotfy/cuckoofilter#30]
Hi everyone, I am working on a project called [infinicache](https://github.com/mason-leap-lab/infinicache), which uses this filter. The system is composed from a Client a Proxy and some Nodes. The client is the one which uses the filter. I modified some code on the proxy side (very little modifications, I just added a field to a structure) and is 2 days now since the cuckoo filter gives problems. Basically when I run the client file, I obtain this.
``` 
$ go run client/example/main.go
# github.com/seiflotfy/cuckoofilter
../pkg/mod/github.com/seiflotfy/cuckoofilter@v0.0.0-20200323075608-c8f23b6b6cef/util.go:17:14: invalid operation: 1 << i (shift count type int, must be unsigned integer)
```
Given that I am not a pro of Golang, I am do not understand very well which kind of error is it. For sure it talks about cuckoofilter, so for me it seems a compile error, but I am not sure about that. Basically I am not able to log anything to the screen when I run the file, so that's why I think is a compile errror. However, I didn't see any change on your master branch since 24 days, hence the library code should have not changed.

Please help me in understanding why I have this error.

Thanks in advance

**Comment by neboduus** [comment]
Most probably the problem comes from the indicated util.go file. I am supposing that the only thing that is needed is to modify the `init()` method in the following way:
```go
func init() {
        .....
	for i := 0; i <= 64; i++ {
		masks[i] = (1 << uint(i)) - 1
	}
}
```
where you can notice I substituted `i` with `uint(i)`.
I d not know if this is the problem, is the only thing I can think at right now

**Comment by neboduus** [comment]
Yes, I confirm that this was the proble. I just thested the proposed solution and it works. I have not time right now to do a merge request, however if you do not manage to fix it, I will propose a commit in the future. Thanks for the work on this lib.

**Comment by seiflotfy** [comment]
acknowledged i patched it :D
thanks for the finding and please confirm it works :D

**Comment by neboduus** [comment]
I confirm it does :)
