### ISSUE TITLE
Effective Method Naming

### ISSUE THREAD

**Issue by trichner** [seiflotfy/cuckoofilter#4]
just an fyi, according to https://golang.org/doc/effective_go.html#Getters you can drop the `Get` in getters i.e. `GetCount()` becomes `Count()`

Thanks for the package!

**Comment by seiflotfy** [comment]
Thanks dude, will take care of it in the morning :D

**Comment by seiflotfy** [comment]
is there a way i can reach you via private msg?

**Comment by trichner** [comment]
I sent you a mail, you can figure out mail addresses by inspecting commits with `git log` :)
